services:
  mysql:
    image: mysql:latest
    container_name: mysql-docker 
    environment:
      MYSQL_ROOT_PASSWORD: abhi
      MYSQL_DATABASE: bank_db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] 
      timeout: 20s
      retries: 10

  node-app:
    build: ./
    container_name: todo-app 
    volumes:
      - ./server.log:/app/server.log
    ports:
      - "3000:3000" 
    depends_on:
      mysql:
        condition: service_healthy        
    networks:
      - app-network

networks:
  app-network:
    driver: bridge