version: '3.9'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf 

  mongoDB:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017" 

volumes:
  redis-data: